name: terraform

on:
  pull_request:
    paths:
      - "infra/**"
  push:
    branches:
      - main
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1

defaults:
  run:
    shell: bash
    working-directory: infra/envs/sandbox

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::637296172968:role/github-actions-grccloud
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform format check
        run: terraform fmt -check -recursive
        working-directory: ../../../infra
      - name: Terraform initialize
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -no-color
      - name: Terraform apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve